/*
 * Copyright (c) 2025, Texas Instruments Incorporated
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * *  Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * *  Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * *  Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 * OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef MODEL_H
#define MODEL_H

/* ============================================================
 * Model-specific convolution geometry
 * (Autogenerated per model configuration)
 * ============================================================ */

/* Input channels (for now assume 1; future-proofed) */
#define MODEL_IN_CHANNELS            (1u)

/* Convolution output channels */
#define MODEL_CONV_OUT_CHANNELS      (64u)

/* Time-domain convolution kernel & stride (in samples) */
#define MODEL_CONV_KERNEL_T          (256u)
#define MODEL_CONV_STRIDE_T          (16u)

/* Hardware constraint: channels computed per iteration */
#define MODEL_MAX_OUT_CH_PER_ITER    (32u)
// TERNARY AND 8 BIT

/* ============================================================
 * Parameter memory layout (TinieLite-specific)
 * ============================================================ */

#define MODEL_MAX_PARAMS_WORDS       (256u)
#define MODEL_DUMMY_TMA_INIT_WORDS   (2u)
#define MODEL_PARAMS_WORDS_PER_ITER  (256u) 

/* ============================================================
 * Assumptions (documented, not derived)
 * ============================================================ */

/* Feature vector length equals conv output channels */
#define MODEL_FBANK_LEN              (MODEL_CONV_OUT_CHANNELS)

/* Weight precision (fixed for now) */
#define MODEL_WEIGHT_BITS            (2u)

#endif /* MODEL_H */